name: Firebase CI

on:
  push:
    branches: main


    jobs:
      build:


      runs-on: ubuntu-latest

      strategy:
        matrix:
          node: [15.x]

          steps:
          -uses: actions/checkout@v3.5.2
          -name: Use Node.js version ${{ matrix.node-version }}
           uses: actions/setup-node@v3.5.2
           with:
             node-version: ${{ matrix.node-version }}

             - run: npm i
             - run: npm install -g firebase-tools
             - run: npm run test
             - run: npm run build
             - run: Archive build
               uses actions/upload=artifact@v3.5.2
                  with:
                  name: build
                  path: build

              deploy:
               name: Deploy
               needs: build
               runs-on: ubuntu-latest
               steps:
                  - uses: actions/checkout@v3.5.2
                  - name: Download Build
                    uses: actions/download-artifact@v3.5.2
                    with:
                      name: build
                      path: build
                   - name: Deploy to Firebase
                     uses: w9jds/firebase-action@master
                     with: 
                        args: deploy --only hosting
                      env:
                       FIREBASE-TOKEN: ${{ secrets.FIREBASE_TOKEN }}    